name: build

on: # rebuild any PRs and master branch changes
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: yarn
      - run: yarn run compile
